name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: mobsfscan
      uses: MobSF/mobsfscan@0.0.8
      with:
        args: '. --sarif --output results.sarif || true'
    - name: Build with Gradle
      run: ./gradlew assembleRelease -PRELEASE_MAPS_MAPCACHE_API_KEY=${{ secrets.RELEASE_MAPS_MAPCACHE_API_KEY }}
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: mapcache/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Copy Release Artifacts
      run: |
        mkdir mapcache/build/release
        cp mapcache/build/outputs/apk/release/mapcache-*-signed.apk "mapcache/build/release/mapcache-$(./gradlew mapcache:androidAppVersion | grep versionName | sed 's/^.*@//').apk"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: mapcache
        path: mapcache/build/release
